networks:
  ln:

services:

  postgres:
    image: postgres:14.10-alpine3.19
    container_name: order_core_postgres
    restart: always
    ports:
      - 15432:5432
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-senha123}
      PGDATA: /data/postgres
    networks:
      - ln

  rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: order_rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - ln