server:
  port: 8383

spring:
  application:
    name: order-core

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: senha123
    url: jdbc:postgresql://localhost:5432/order_core_database
    platform: postgres
    initialization-mode: always
    continue-on-error: true

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.globally_quoted_identifiers: true

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: queue_order
  exchange: exchanges_order
  routing: routing-key-teste

springdoc:
  api-docs:
    path: /api-docs

  pathsToMatch:
    - /auth/**
    - /api/**

  swagger-ui:
    use-root-path: true
